# Generated by Django 4.0.2 on 2022-02-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_no', models.IntegerField(max_length=30)),
                ('b_title', models.CharField(max_length=1000)),
                ('b_content', models.CharField(max_length=1000)),
            ],
        ),
    ]
