# Generated by Django 4.0.2 on 2022-02-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_no',
            field=models.IntegerField(default=1),
        ),
    ]
