# Generated by Django 4.0.2 on 2022-02-26 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stboard', '0002_alter_board_b_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='id',
        ),
        migrations.AddField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 9, 10, 33, 121615)),
        ),
        migrations.AddField(
            model_name='board',
            name='b_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='b_hit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='board',
            name='b_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='board',
            name='b_indent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='b_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='b_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
