# Generated by Django 4.0.2 on 2022-02-26 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stboard', '0003_remove_board_id_board_b_date_board_b_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 26, 9, 11, 31, 579644)),
        ),
    ]
