# Generated by Django 4.0.2 on 2022-03-01 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stboard', '0004_alter_board_b_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 1, 21, 29, 47, 792820)),
        ),
    ]
